joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\salvo\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\externals\loky\process_executor.py", line 490, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "C:\Users\salvo\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\externals\loky\process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\salvo\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\parallel.py", line 607, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
            ^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\salvo\OneDrive\Desktop\model\Newton_Methods_Optimization\Test.py", line 205, in <module>
    Test(n,method,function)
  File "c:\Users\salvo\OneDrive\Desktop\model\Newton_Methods_Optimization\Test.py", line 190, in Test
    run_test(comb,x0)
  File "c:\Users\salvo\OneDrive\Desktop\model\Newton_Methods_Optimization\Test.py", line 154, in run_test
    inner_iter, alphas, tol_seq = computation(comb,function)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\salvo\OneDrive\Desktop\model\Newton_Methods_Optimization\Test.py", line 17, in computation
    execution_times_, xk, fxk, norm_gradfx_seq, k, success, inner_iter, alphas, tol_seq= MNM.Run(timing=True)
                                                                                         ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\salvo\OneDrive\Desktop\model\Newton_Methods_Optimization\Modified_Newton_Method\ModifiedNewtonMethod.py", line 172, in Run
    grad = self.compute_gradient(xk, adaptive=self.adaptive_h)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\salvo\OneDrive\Desktop\model\Newton_Methods_Optimization\Tools\Derivatives.py", line 172, in approximate_gradient_parallel
    grad = Parallel(n_jobs=n_jobs)(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\salvo\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\parallel.py", line 2072, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "C:\Users\salvo\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\parallel.py", line 1682, in _get_outputs
    yield from self._retrieve()
  File "C:\Users\salvo\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\parallel.py", line 1784, in _retrieve
    self._raise_error_fast()
  File "C:\Users\salvo\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\parallel.py", line 1859, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "C:\Users\salvo\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\parallel.py", line 758, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\salvo\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\parallel.py", line 773, in _return_or_raise
    raise self._result
TypeError: 'NoneType' object is not callable
